* User manual

PeriodicRelatedChanges (PRC) provides your MediaWiki wiki with the ability to notify users about changes related to categories or pages they are watching on a daily or weekly basis.

** User Permissions
PRC exposes two new permissions that can be assigned to groups:
- =periodic-related-changes= - View and change the PRC notices for logged in user.
- =periodic-related-changes-any-user= - View and change the PRC notices for any user.

By default, the =periodic-related-changes= right is assigned to the =user= group so that any logged in user can view and modify their own PRC notices; the =periodic-related-changes-any-user= right is assigned to the =sysop= (often displayed as "administrator" on the wiki) group.

If you want to take the rights away from these groups you would do something like the following in your LocalSettings.php:
#+BEGIN_SRC php
// Take away the default rights
$wgGroupPermissions['user']['periodic-related-changes'] = false;
$wgGroupPermissions['sysop']['periodic-related-changes-any-user'] = false;

// Give them to other groups
$wgGroupPermissions['watchers']['periodic-related-changes'] = true;
$wgGroupPermissions['watch-admin']['periodic-related-changes-any-user'] = true;
#+END_SRC

** Setting up notifications

When a user visits Special:PeriodicRelatedChanges on your wiki, they'll see one of three things, depending on their permission level.  The default configuration would show these options:

- *A form to look up a user* Administrators will see this when they first visit the page. Auto-completion of the user name is provided.
- *A form to edit the the pages on a user's PRC list* Logged in users that are not administrators will see this page with their own PRC list.  Administrators will see this page once they have selected a user.
- *Permission error* Users who are not logged in will be told that they cannot access this featurae.


** Importing a list of bulk watchers
** What counts as a related page
** Changing the email formats
